### ISSUE TITLE
access grin-node running on hosting sever in grin-wallet

### ISSUE THREAD

**Issue by aifeelit** [MimbleWimble-Grin/api-test-grin-wallet-react#1]

**Comment by wp-dream111** [comment]
modify grin-wallet config file

**Comment by grisha-leader** [comment]
Please, take a look at C:/Users/"User-name" .grin folder

**Comment by grisha-leader** [comment]
.grin-node and .grin-wallet
there's toml file and set the rpc_remote_ip to 0.0.0.1

**Comment by WeiLong701** [comment]
Awesome!
It is originally set as 127.0.0.1
Works well. Thanks pal. Rishali?!

**Comment by grisha-leader** [comment]
lol rishali?

**Comment by aifeelit** [comment]
Well done!
